// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoUsuario.Persistence.Context;

#nullable disable

namespace ProjetoUsuario.Persistence.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoUsuario.Domain.Entidades.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DescricaoPerfil")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao_perfil");

                    b.Property<bool>("IndicadorPerfil")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("indicador_perfil");

                    b.HasKey("Id");

                    b.ToTable("perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
